# Generated by Django 5.2.1 on 2025-06-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0002_alter_product_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='CartItem',
        ),
    ]
